export default {
  quality: 2,
  enableAntialias:true,
  ctrlSpeed: 2,
  enableDamping:true,
  dampingFactor:0.1,
  maxZoom: 1000,
  minZoom: 100,
  maxPolarAngle: 1.5,
  minPolarAngle: 0,
  autoRotate: false,
  autoRotateSpeed: 5,
  cameraTweenSpeed: 1500,
  TargetTweenSpeed: 2000,
  voiceSpeed: 1,
  voicePitch: 1,
  voiceLevel: 1,
  developmentModel: false,
};
